### ISSUE TITLE
Facebook login is down

### ISSUE THREAD

**Issue by juanpabloe** [CodeandoMexico/codeandomexico.org#80]
The callback is crashing. Returning empty array.

Logs 

```
2016-04-13T13:42:39.036093+00:00 app[web.1]:
2016-04-13T13:42:39.036101+00:00 app[web.1]: NoMethodError (undefined method `[]' for nil:NilClass):
2016-04-13T13:42:39.036107+00:00 app[web.1]:   app/models/authentication.rb:28:in `create_with_omniauth'
2016-04-13T13:42:39.036110+00:00 app[web.1]:   app/models/authentication.rb:8:in `find_for_provider_oauth'
2016-04-13T13:42:39.036109+00:00 app[web.1]:   app/models/authentication.rb:21:in `find_or_create_with_omniauth'
2016-04-13T13:42:39.036518+00:00 app[web.1]: cache: [GET /users/auth/facebook/callback?code=x&state=ae39d5e93d560fbd3c596650f19ce76767020a109dba1284] miss
2016-04-13T13:42:39.036111+00:00 app[web.1]:
2016-04-13T13:42:39.036111+00:00 app[web.1]:
2016-04-13T13:42:39.036110+00:00 app[web.1]:   app/controllers/users/omniauth_callbacks_controller.rb:6:in `all'
```

**Comment by kyleboss** [comment]
The bug is fixed and will be patched with the UCB-ITEM branch merge into master :) 

Culprit was a change to the FB API. More info can be found here: https://developers.facebook.com/docs/apps/changelog#v2_4
